module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: [
    'react-native-reanimated/plugin',
    [
      'module-resolver',
      {
        alias: {
          '@app': './app',
          '@screens': './app/screens',
          '@components': './app/components',
          '@theme': './app/theme',
          '@hooks': './app/hooks',
          '@utils': './app/utils',
          '@store': './app/store',
        },
        extensions: [
          '.ios.ts',
          '.android.ts',
          '.ts',
          '.ios.tsx',
          '.android.tsx',
          '.tsx',
          '.jsx',
          '.js',
          '.mjs',
          '.cjs',
          '.ios.js',
          '.android.js',
          '.json',
          '.png',
          '.jpg',
          '.webp',
          '.gif',
          '.svg',
          '.ttf',
          '.mp3',
          '.mp4',
          '.d.ts',
        ],
      },
    ],
  ],
};
